environments:
  development:
    pipelines:
      - chef-rsyslog
pipelines:
  chef-rsyslog:
    group: development
    materials:
      gitMaterial1:
        git: git@github.com:kinesisptyltd/chef-rsyslog.git
    stages:
      - test:
          jobs:
            test:
              tasks:
                - exec:
                    command: bash
                    arguments:
                    - -c
                    - 'curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -v 1.3.43 -P chefdk'
                - exec:
                    command: chef
                    arguments:
                    - exec
                    - bundle
                    - install
                - exec:
                    command: chef
                    arguments:
                    - exec
                    - bundle
                    - exec
                    - kitchen
                    - verify
