---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[rsyslog::default]
      - recipe[rsyslog::papertrail]
      - recipe[rsyslog::provider_test]
    attributes:
